# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpuser_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PimpUserMessageReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('reply_body', tinymce.models.HTMLField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pimpuser_messages.PimpUserMessage')),
            ],
        ),
    ]
