# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pimpuser_messages', '0002_pimpusermessagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpusermessagereply',
            name='reply_sender',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reply_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
