# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpuser_messages', '0003_pimpusermessagereply_reply_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpusermessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pimpusermessagereply',
            name='reply_body',
            field=models.TextField(),
        ),
    ]
