# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpuser_messages', '0006_auto_20180224_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpusermessage',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='read at'),
        ),
    ]
