# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpuser_messages', '0007_pimpusermessage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpusermessage',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
    ]
