# Generated by Django 4.2.16 on 2025-10-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpuser_messages', '0008_auto_20180323_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpusermessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pimpusermessagereply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
