# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0025_auto_20170409_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('cause_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.CauseProfile')),
                ('skill', models.ManyToManyField(blank=True, related_name='advert_skill', to='profiles.Skill')),
            ],
        ),
    ]
