# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-02 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='id',
        ),
        migrations.AlterField(
            model_name='advert',
            name='cause_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.CauseProfile'),
        ),
    ]
