# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20170508_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='image',
        ),
    ]
