# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-08 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20170408_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
