# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_remove_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
