# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-08 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20170408_0104'),
        ('adverts', '0004_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='cause_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.CauseProfile'),
            preserve_default=False,
        ),
    ]
