# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_auto_20180225_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
