# Generated by Django 2.2 on 2021-09-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_auto_20180225_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='cause_profile',
            field=models.ForeignKey(limit_choices_to={'profile__usertype': 1}, on_delete=django.db.models.deletion.CASCADE, to='profiles.CauseProfile'),
        ),
    ]
