# Generated by Django 4.2.16 on 2025-10-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0009_auto_20210926_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
