# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import news.fields
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', news.fields.HTMLField()),
            ],
        ),
    ]
