# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='description',
            new_name='content',
        ),
    ]
