# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170909_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, verbose_name='slug'),
        ),
    ]
