# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug'),
        ),
    ]
