# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170909_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='intro',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
