# Generated by Django 4.2.16 on 2025-10-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180124_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
