# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-24 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
