# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='visual_priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=1),
            preserve_default=False,
        ),
    ]
