# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('surname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=85)),
                ('position', models.CharField(max_length=85)),
                ('usertype', models.CharField(choices=[('MKTR', 'Marketer'), ('CAUSE', 'Cause')], max_length=8)),
                ('twitter', models.CharField(max_length=30)),
            ],
        ),
    ]
