# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pimp_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=85)),
                ('postcode', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=85)),
                ('usertype', models.CharField(choices=[('MKTR', 'Marketer'), ('CAUSE', 'Cause')], max_length=8)),
                ('twitter', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='pimp_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
