# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160730_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpuser',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='city',
            field=models.CharField(blank=True, max_length=85),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='experience',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='phone',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='qualifications',
            field=models.CharField(blank=True, choices=[(0, 'Advertising'), (1, 'Branding'), (2, 'Business Development'), (3, 'Customer Insights'), (4, 'Digital Marketing'), (5, 'Graphic Design'), (6, 'Innovation'), (7, 'Marketing'), (8, 'Photography'), (9, 'PR'), (10, 'SEO'), (11, 'Social Media Marketing'), (12, 'Strategic Marketing'), (13, 'Videography'), (14, 'Web Development')], max_length=8),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='surname',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='usertype',
            field=models.CharField(blank=True, choices=[(0, 'Marketer'), (1, 'Cause')], max_length=8),
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
