# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160730_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
