# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 18:11
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160731_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpuser',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
