# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160731_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MarketerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.CharField(blank=True, choices=[(0, 'Advertising'), (1, 'Branding'), (2, 'Business Development'), (3, 'Customer Insights'), (4, 'Digital Marketing'), (5, 'Graphic Design'), (6, 'Innovation'), (7, 'Marketing'), (8, 'Photography'), (9, 'PR'), (10, 'SEO'), (11, 'Social Media Marketing'), (12, 'Strategic Marketing'), (13, 'Videography'), (14, 'Web Development')], max_length=8)),
                ('experience', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='pimpuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='pimpuser',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='marketeruser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='causeuser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
