# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160904_1843'),
        ('profiles', '0007_pimpuser_image'),
    ]

    operations = [
    ]
