# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketerprofile',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
