# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_marketerprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpuser',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
