# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_pimpuser_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
