# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20160926_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causeprofile',
            name='categories',
            field=models.CharField(blank=True, choices=[(0, 'Disaster Relief'), (1, 'Poverty Alleviation'), (2, 'Environment'), (3, 'Education and Skills'), (4, 'Animal Welfare'), (5, 'Children and Youth'), (6, 'Disability'), (7, 'Health'), (8, 'Food'), (9, 'Family Support'), (10, 'Care for the Eldery')], max_length=8),
        ),
    ]
