# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20160926_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advertising', models.BooleanField(default=True)),
                ('Branding', models.BooleanField(default=False)),
                ('BusinessDevelopment', models.BooleanField(default=False)),
                ('CustomerInsights', models.BooleanField(default=False)),
                ('DigitalMarketing', models.BooleanField(default=False)),
                ('GraphicDesign', models.BooleanField(default=False)),
                ('Innovation', models.BooleanField(default=False)),
                ('Marketing', models.BooleanField(default=False)),
                ('PR', models.BooleanField(default=False)),
                ('SEO', models.BooleanField(default=False)),
                ('SocialMediaMarketing', models.BooleanField(default=False)),
                ('StrategicMarketing', models.BooleanField(default=False)),
                ('Videography', models.BooleanField(default=False)),
                ('WebDevelopment', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketerprofile',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='marketerprofile',
            name='qualification',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Qualification'),
            preserve_default=False,
        ),
    ]
