# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20161016_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='Advertising',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='Branding',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='BusinessDevelopment',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='CustomerInsights',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='DigitalMarketing',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='GraphicDesign',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='Innovation',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='Marketing',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='PR',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='SEO',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='SocialMediaMarketing',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='StrategicMarketing',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='Videography',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='WebDevelopment',
        ),
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 10, 16, 18, 41, 27, 415962, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='marketerprofile',
            name='qualification',
        ),
        migrations.AddField(
            model_name='marketerprofile',
            name='qualification',
            field=models.ManyToManyField(to='profiles.Qualification'),
        ),
    ]
