# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20161016_1841'),
        ('profiles', '0012_auto_20161006_2130'),
    ]

    operations = [
    ]
