# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketerprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='marketerprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
