# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20161023_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpuser',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='usertype',
            field=models.IntegerField(choices=[(0, 'Marketer'), (1, 'Cause')], default=1),
            preserve_default=False,
        ),
    ]
