# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20161023_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='usertype',
            field=models.IntegerField(choices=[(0, 'Marketer'), (1, 'Cause')], default=0),
            preserve_default=False,
        ),
    ]
