# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-05 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20170215_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimpuser',
            name='slug',
        ),
    ]
