# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-08 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20170408_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='usertype',
            field=models.IntegerField(choices=[(0, 'Marketer'), (1, 'Cause'), (2, 'Admin')], default=0),
        ),
    ]
