# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-08 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20170408_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='causeprofile',
            name='cause_name',
            field=models.CharField(default='Cause name', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketerprofile',
            name='qualification',
            field=models.ManyToManyField(blank=True, to='profiles.Qualification'),
        ),
    ]
