# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20170408_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='marketerprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='profiles.Skill'),
        ),
    ]
