# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-24 18:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20170409_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpuser',
            name='latitude',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='longtitude',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
            preserve_default=False,
        ),
    ]
