# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 00:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_pimpuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
