# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 22:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20171021_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimpuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pimpuser',
            name='longtitude',
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
