# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20171022_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causeprofile',
            name='cause_name',
        ),
        migrations.AddField(
            model_name='pimpuser',
            name='cause_name',
            field=models.CharField(default='Test Cause', max_length=1000),
            preserve_default=False,
        ),
    ]
