# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20171228_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='cause_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
