# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20171228_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='cause_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
