# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20180112_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpuser',
            name='geo_data',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='twitter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
