# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20180203_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='city',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='surname',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
