# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20180203_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
