# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20180203_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='geo_data',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
