# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20180203_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimpuser',
            name='name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='surname',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
