# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20180203_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causeprofile',
            name='mission',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
