# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20180211_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketerprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
