# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_auto_20180218_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimpuser',
            name='has_reactivated',
            field=models.BooleanField(default=False),
        ),
    ]
