# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_pimpuser_has_reactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
