# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_auto_20180224_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='marketer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banana', to='profiles.MarketerProfile'),
        ),
        migrations.AlterField(
            model_name='marketerprofile',
            name='qualification',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Qualification'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
