# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 15:16
from __future__ import unicode_literals

from django.db import migrations


def copy_marketer_profile_id(apps, schema_editor):
    MarketerProfile = apps.get_model('profiles', 'MarketerProfile')

    for profile in MarketerProfile.objects.all():
        qualifications = profile.qualification.all()
        print(qualifications)

        for q in qualifications:
            q.marketer = profile
            q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_auto_20180224_1507'),
    ]

    operations = [
        migrations.RunPython(copy_marketer_profile_id)
    ]
