# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_auto_20180224_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketerprofile',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.MarketerProfile'),
        ),
    ]
