# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20180224_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
