# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_auto_20180218_1553'),
        ('profiles', '0054_auto_20180224_2347'),
    ]

    operations = [
    ]
