# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_merge_20180225_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
