# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20180225_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='start_date',
        ),
    ]
