# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 22:20
from __future__ import unicode_literals

from django.db import migrations


def rename_user_image_files(apps, schema_editor):
    Pimpuser = apps.get_model('profiles', 'Pimpuser')

    for user in Pimpuser.objects.all():
        if user.image:
            print(user.image)
            user.image = user.image.replace(' ', '-')
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20180225_1519'),
    ]

    operations = [
        migrations.RunPython(rename_user_image_files)
    ]
